export const locationTypeLabels: Record<string, string> = {
    vodospad: "Водоспад",
    hory: "Гори",
    more: "Море",
    "miskyi-vidpochynok": "Міський відпочинок",
    ozero: "Озеро",
    lis: "Ліс",
    richka: "Річка",
    plyazh: "Пляж",
    "istorychne-mistse": "Історичне місце",
    "termalni-dzherela": "Термальні джерела",
    "spa-kurort": "Спа-курорт",
    "hirskolyzhnyi-kurort": "Гірськолижний курорт",
    zamok: "Замок",
    "natsionalnyi-park": "Національний парк",
    zapovidnyk: "Заповідник",
    pechera: "Печера",
};

export const regionLabels: Record<string, string> = {
    zakarpattya: "Закарпаття",
    odeshchyna: "Одещина",
    khersonshchyna: "Херсонщина",
    "chornomorske-uzberezhzhya": "Чорноморське узбережжя",
    kyyivshchyna: "Київщина",
    "shatski-ozera": "Шацькі озера",
    bukovyna: "Буковина",
    mykolayivshchyna: "Миколаївщина",
    zhytomyrshchyna: "Житомирщина",
    "dnistrovskyi-kanyon": "Дністровський каньйон",
    rivnenshchyna: "Рівненщина",
    hutsulshchyna: "Гуцульщина",
    chernihivshchyna: "Чернігівщина",
    lvivshchyna: "Львівщина",
    "ivano-frankivshchyna": "Івано-Франківщина",
    "ukrainski-karpaty": "Українські Карпати",
    ternopilshchyna: "Тернопільщина",
    cherkashchyna: "Черкащина",
    poltavshchyna: "Полтавщина",
    khmelnychchyna: "Хмельниччина",
};